### ISSUE TITLE
BE - Orders

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#11]
**Given**:
User exists

**When**:
User wants to create an order

**Then**:
Order is successfully created

**Tasks**:
- [x] Create models Order (table 'orders') and OrderStatus('order_statuses'), connect Order model with 'companies', 'users' and 'couriers' tables
- [x] Create OrderRepository, OrderService and OrderController
- [x] Create endpoints in OrderController to create, get, edit and delete order

**Acceptance criteria**:

**Comment by MikeMalyar** [comment]
Testing is blocked by #40
