### ISSUE TITLE
BE - Companies

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#12]
**Given**:
User exists

**When**:
User wants to create a company

**Then**:
Company is successfully created, user becomes a company owner

**Tasks**:
- [x] Create model Company (table 'companies'), connect it with 'users' and 'couriers' tables, see #7 
- [x] Create CompanyRepository, CompanyService and CompanyController
- [x] Create endpoints in CompanyController to create, get, edit, delete and enable a company

**Acceptance criteria**:
- When company is created, it's disabled, and becomes enable after checking it by moderator
- When company is created by user firstly, user becomes a company owner
- Controller should return GenericResponse with correct result or message.
