### ISSUE TITLE
BE - Users registration

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#19]
**Given**:
User wants to register

**When**:
User submits a register form

**Then**:
Register logic is called

**Tasks**:
- [x] Update registration logic
- [x] Create a VerificationToken model that will be created when user registers
- [x] Create logic to confirm registration (from email basically)

**Acceptance criteria**:
