### ISSUE TITLE
BE - Mail sending

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#20]
**Given**:
Some changes occurred

**When**:
Email should be sent

**Then**:
Email is successfully sent

**Tasks**:
- [x] Create and configure EmailService
- [x] Create basic and registration email templates
- [x] Call this service with registration confirmation link when user is registered

**Acceptance criteria**:
- Attachments and links can be added to email
