### ISSUE TITLE
BE - Requests validation

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#25]
**When**:
Some request is called

**Then**:
Request data is validated

**Tasks**:
- [x] Create validation logic
- [x] Annotate required validations on model fields
- [ ] Validate data where request is started to proceed and return response with information about validation error if it's occurred

**Acceptance criteria**:
