### ISSUE TITLE
FE - Create login and registration pages

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#55]
**Given**:

**When**:

**Then**:

**Tasks**:
- [x] Create user login page
- [x] Create user registration page
- [x] Make login page default for unauthorized response. 

**Acceptance criteria**:
