### ISSUE TITLE
FE - Create maket home page

### ISSUE THREAD

**Issue by ozhga1999** [MikeMalyar/PrimumPartusApp#66]
- [x] Create maket home page

- [x] Home page includes three block: header, content, footer 

- [x] Header includes: logotype, menu bar and login buttons 

- [x] Contact information

**When**:

**Then**:

**Tasks**:

**Acceptance criteria**:
