### ISSUE TITLE
BE - Users Authentication

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#8]
**Given**:
An user exists

**When**:
1. User logins
2. User registers

**Then**:
1. Logic checks if user exist in db with those email and password, if account is enabled etc.
2. Logic register a user (without email verification), password is encrypted before saving in db

**Tasks**:
- [x] Create model User (table 'users') and model Role (table 'roles'), see #7 , connect this tables
- [x] Create UserRepository, UserService, UserController
- [x] Create endpoints in UserController for user login, logout and register
- [x] Configure Spring Security
- [x] When user logins, access token is generated, user is saved in session

Other tasks may be discussed later

**Acceptance criteria**:
- Use Spring Security
- Password is encrypted before saving in db
