### ISSUE TITLE
BE - User Profiles

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#9]
**Given**:
User exists

**When**:
1. User is registered
2. User updates a profile

**Then**:
1. Profile is created
2. Profile is successfully updated

**Tasks**:
- [x] Create model Profile (table 'profiles'), see #7 , connect it with 'users' table
- [x] Create ProfileRepository, ProfileService, ProfileController
- [x] Create endpoints to get and edit profile

**Acceptance criteria**:
